/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownFee } from './GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownFee';
import { Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownTax } from './GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownTax';

export class Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdown {
    'fee'?: Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownFee;
    'tax'?: Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownTax;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fee",
            "baseName": "fee",
            "type": "Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownFee"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdownTax"
        }    ];

    static getAttributeTypeMap() {
        return Finance202501GetTransactionsbyOrderResponseDataSkuTransactionsFeeTaxBreakdown.attributeTypeMap;
    }
}

