/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202409PartialEditManufacturerRequestBodyPhoneNumber } from './PartialEditManufacturerRequestBodyPhoneNumber';

export class Product202409PartialEditManufacturerRequestBody {
    /**
    * The postal address of the manufacturer. Max length: 500 characters
    */
    'address'?: string;
    /**
    * The email address of the manufacturer.
    */
    'email'?: string;
    /**
    * The BCP-47 locale code representing the language used for specifying the responsible person information. Possible values: - de-DE - en-IE - es-ES - fr-FR - it-IT Default: The locale of the seller\'s registered business address.  **Note**: The information provided will be automatically translated into all EU languages supported by TikTok Shop. Ensure the locale matches the language used in field values to avoid inaccurate translations.
    */
    'locale'?: string;
    /**
    * The manufacturer name. Max length: 255 characters
    */
    'name'?: string;
    'phoneNumber'?: Product202409PartialEditManufacturerRequestBodyPhoneNumber;
    /**
    * The registered trade name of the manufacturer. Max length: 200 characters
    */
    'registeredTradeName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "Product202409PartialEditManufacturerRequestBodyPhoneNumber"
        },
        {
            "name": "registeredTradeName",
            "baseName": "registered_trade_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202409PartialEditManufacturerRequestBody.attributeTypeMap;
    }
}

