/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202507ReplicateProductRequestBodyReplicateTargetSkusInventory } from './ReplicateProductRequestBodyReplicateTargetSkusInventory';
import { Product202507ReplicateProductRequestBodyReplicateTargetSkusPrice } from './ReplicateProductRequestBodyReplicateTargetSkusPrice';

export class Product202507ReplicateProductRequestBodyReplicateTargetSkus {
    /**
    * SKU inventory information per warehouse. This field is only required if the inventory allocation mode for the warehouse is MANUAL. Otherwise, it is optional.
    */
    'inventory'?: Array<Product202507ReplicateProductRequestBodyReplicateTargetSkusInventory>;
    'price'?: Product202507ReplicateProductRequestBodyReplicateTargetSkusPrice;
    /**
    * The ID of the SKU being replicated
    */
    'sourceSkuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202507ReplicateProductRequestBodyReplicateTargetSkusInventory>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202507ReplicateProductRequestBodyReplicateTargetSkusPrice"
        },
        {
            "name": "sourceSkuId",
            "baseName": "source_sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202507ReplicateProductRequestBodyReplicateTargetSkus.attributeTypeMap;
    }
}

