/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202407SearchSizeChartsResponseDataSizeChartImages {
    /**
    * The language of the size chart image.
    */
    'locale'?: string;
    /**
    * The URI to identify the image in API requests and responses.
    */
    'uri'?: string;
    /**
    * The URL to access and view the image.
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string"
        },
        {
            "name": "uri",
            "baseName": "uri",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202407SearchSizeChartsResponseDataSizeChartImages.attributeTypeMap;
    }
}

