/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Open202512UploadFileInitRequestBody {
    /**
    * file name
    */
    'fileName'?: string;
    /**
    * file size, bytes
    */
    'fileSize'?: number;
    /**
    * Supported file types. current only support video
    */
    'fileType'?: string;
    /**
    * After the video is uploaded, use this interface to bind the video resource to the specific material 
    */
    'targetPath'?: string;
    /**
    * The total number of chunks.
    */
    'totalChunkCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string"
        },
        {
            "name": "fileSize",
            "baseName": "file_size",
            "type": "number"
        },
        {
            "name": "fileType",
            "baseName": "file_type",
            "type": "string"
        },
        {
            "name": "targetPath",
            "baseName": "target_path",
            "type": "string"
        },
        {
            "name": "totalChunkCount",
            "baseName": "total_chunk_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Open202512UploadFileInitRequestBody.attributeTypeMap;
    }
}

