/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202309CalculateRefundResponseDataOrderRefundAmount } from './CalculateRefundResponseDataOrderRefundAmount';

export class ReturnRefund202309CalculateRefundResponseData {
    'orderRefundAmount'?: ReturnRefund202309CalculateRefundResponseDataOrderRefundAmount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderRefundAmount",
            "baseName": "order_refund_amount",
            "type": "ReturnRefund202309CalculateRefundResponseDataOrderRefundAmount"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309CalculateRefundResponseData.attributeTypeMap;
    }
}

