/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetProductResponseDataProductAttributesValues } from './GetProductResponseDataProductAttributesValues';

export class Product202309GetProductResponseDataProductAttributes {
    /**
    * The ID of the product attribute.
    */
    'id'?: string;
    /**
    * The product attribute name.
    */
    'name'?: string;
    /**
    * A list of selectable values for the product attribute.
    */
    'values'?: Array<Product202309GetProductResponseDataProductAttributesValues>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Product202309GetProductResponseDataProductAttributesValues>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataProductAttributes.attributeTypeMap;
    }
}

