/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309RecommendGlobalCategoriesRequestBodyImages } from './RecommendGlobalCategoriesRequestBodyImages';

export class Product202309RecommendGlobalCategoriesRequestBody {
    /**
    * The category tree version to use for this product. Possible values based on region: - US: `v2`, represents the 7-level category tree.   **Important**: If the seller account contains an active US shop, you must pass `v2` when using this API. - Other regions: `v1`, represents the 3-level category tree. Default: `v1`
    */
    'categoryVersion'?: string;
    /**
    * The product description in HTML format.  **Note**: - The content must conform to the [HTML syntax](https://html.spec.whatwg.org/). All HTML tags are accepted but to optimize display on the TikTok Shop product detail page, the system will automatically convert certain tags into alternative formats, such as rendering `<table>` tags as images. - Max length: 10,000 characters. - Image guidelines: You must use [TikTok Shop image URLs](6509df95defece02be598a22). Max 30 `<img>` tags, each under 4000px with `src`, `width`, and `height` attributes.  **Recommendations**:  - If you are syncing a pre-existing description from another platform, include the full HTML source description here. - Provide a detailed description, ideally over 300 characters. - Include 3-5 key selling points, each under 250 characters, with supporting images. - Use 1600x1600 px for the image dimensions.
    */
    'description'?: string;
    /**
    * Product images, including gallery images, images that appear in the description, product variant images. 
    */
    'images'?: Array<Product202309RecommendGlobalCategoriesRequestBodyImages>;
    /**
    * The product title.  Title length: - DE, ES, FR, IE, IT, JP, UK, US: [1, 255]  - MX:[1,300]  - Other regions: [25, 255] 
    */
    'productTitle'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryVersion",
            "baseName": "category_version",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202309RecommendGlobalCategoriesRequestBodyImages>"
        },
        {
            "name": "productTitle",
            "baseName": "product_title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309RecommendGlobalCategoriesRequestBody.attributeTypeMap;
    }
}

