/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202312SearchGlobalProductsResponseDataGlobalProducts } from './SearchGlobalProductsResponseDataGlobalProducts';

export class Product202312SearchGlobalProductsResponseData {
    /**
    * The list of global products that meet the query conditions.
    */
    'globalProducts'?: Array<Product202312SearchGlobalProductsResponseDataGlobalProducts>;
    /**
    * An opaque token used to retrieve the next page of a paginated result set. Provide this value in the `page_token` parameter of your request if the current response does not return all the results.
    */
    'nextPageToken'?: string;
    /**
    * The total number of global products that meet the query conditions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "globalProducts",
            "baseName": "global_products",
            "type": "Array<Product202312SearchGlobalProductsResponseDataGlobalProducts>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202312SearchGlobalProductsResponseData.attributeTypeMap;
    }
}

