/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202312SearchGlobalProductsResponseDataGlobalProductsSkus } from './SearchGlobalProductsResponseDataGlobalProductsSkus';

export class Product202312SearchGlobalProductsResponseDataGlobalProducts {
    /**
    * The time when the product is created. Unix timestamp. 
    */
    'createTime'?: number;
    /**
    * The global product ID in TikTok Shop.
    */
    'id'?: string;
    /**
    * A list of global Stock Keeping Units (SKUs) used to identify distinct variants of the product.
    */
    'skus'?: Array<Product202312SearchGlobalProductsResponseDataGlobalProductsSkus>;
    /**
    * The status of the product. Possible values: - PUBLISHED - UNPUBLISHED - DRAFT - DELETED
    */
    'status'?: string;
    /**
    * The product title.
    */
    'title'?: string;
    /**
    * The time when the product is last updated. Unix timestamp.
    */
    'updateTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202312SearchGlobalProductsResponseDataGlobalProductsSkus>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202312SearchGlobalProductsResponseDataGlobalProducts.attributeTypeMap;
    }
}

