/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus {
    /**
    * TikTok Shop SKU ID
    */
    'id'?: string;
    /**
    * The quantity of each SKU
    */
    'quantity'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SupplyChain202309ConfirmPackageShipmentRequestBodyPackagesSkus.attributeTypeMap;
    }
}

