/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202407ListingSchemasResponseDataListingSchemasFieldsComplexValues } from './ListingSchemasResponseDataListingSchemasFieldsComplexValues';
import { Product202407ListingSchemasResponseDataListingSchemasFieldsOptions } from './ListingSchemasResponseDataListingSchemasFieldsOptions';
import { Product202407ListingSchemasResponseDataListingSchemasFieldsRules } from './ListingSchemasResponseDataListingSchemasFieldsRules';

export class Product202407ListingSchemasResponseDataListingSchemasFields {
    /**
    * List of complex subfield values
    */
    'complexValues'?: Array<Product202407ListingSchemasResponseDataListingSchemasFieldsComplexValues>;
    /**
    * The id of the listing fields. The fields include: title,category, brand, product_attributes, sku.sale_attributes, sku.identifier_code, package_dimensions.
    */
    'id'?: string;
    /**
    * The fields display name.
    */
    'name'?: string;
    /**
    * The list of field options. For optional fields, return all the available options.
    */
    'options'?: Array<Product202407ListingSchemasResponseDataListingSchemasFieldsOptions>;
    /**
    * The rules of the schema\'s fields are used to describe the requirements of the product.
    */
    'rules'?: Array<Product202407ListingSchemasResponseDataListingSchemasFieldsRules>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "complexValues",
            "baseName": "complex_values",
            "type": "Array<Product202407ListingSchemasResponseDataListingSchemasFieldsComplexValues>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<Product202407ListingSchemasResponseDataListingSchemasFieldsOptions>"
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "Array<Product202407ListingSchemasResponseDataListingSchemasFieldsRules>"
        }    ];

    static getAttributeTypeMap() {
        return Product202407ListingSchemasResponseDataListingSchemasFields.attributeTypeMap;
    }
}

