/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202407SearchSizeChartsRequestBody {
    /**
    * Filter size charts by size chart template IDs.  Max: 50 IDs
    */
    'ids'?: Array<string>;
    /**
    * Filter size charts by size chart template name or by key words in the template name. If both `ids` and `keyword` are provided, `ids` takes priority.
    */
    'keyword'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>"
        },
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202407SearchSizeChartsRequestBody.attributeTypeMap;
    }
}

