/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202401ListingSchemasResponseDataListingSchemasFileds } from './ListingSchemasResponseDataListingSchemasFileds';

export class Product202401ListingSchemasResponseDataListingSchemas {
    /**
    * The category id
    */
    'categoryId'?: number;
    /**
    *   The description of the fields in the schema explains the capabilities, rules, and other properties of the fields.
    */
    'fileds'?: Array<Product202401ListingSchemasResponseDataListingSchemasFileds>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "categoryId",
            "baseName": "category_id",
            "type": "number"
        },
        {
            "name": "fileds",
            "baseName": "fileds",
            "type": "Array<Product202401ListingSchemasResponseDataListingSchemasFileds>"
        }    ];

    static getAttributeTypeMap() {
        return Product202401ListingSchemasResponseDataListingSchemas.attributeTypeMap;
    }
}

