/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309EditProductRequestBodyProductAttributesValues {
    /**
    * The ID of the product attribute value. This is either a built-in product attribute value ID from [Get Attributes API](https://partner.tiktokshop.com/docv2/page/6509c5784a0bb702c0561cc8) or a custom product attribute value ID returned after calling [Create Product API](https://partner.tiktokshop.com/docv2/page/6502fc8da57708028b42b18a).
    */
    'id'?: string;
    /**
    * A self-defined custom product attribute value if the built-in values do not satisfy your needs. The system will auto-generate an ID after editing.  **Note**:  - No duplicates allowed under the same attribute. - Max length: 2000 characters
    */
    'name'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditProductRequestBodyProductAttributesValues.attributeTypeMap;
    }
}

