/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309EditProductRequestBodyReplicatedProductsSkus } from './EditProductRequestBodyReplicatedProductsSkus';

export class Product202309EditProductRequestBodyReplicatedProducts {
    /**
    * The market where you want to sync the changes to. The market must already contain a replica. Use the Get Global Replicated Products to check the markets that contain a replica. Possible values: - DE: Germany - ES: Spain - FR: France - GB: United Kingdom - ID: Indonesia - IE: Ireland - IT: Italy - JP: Japan - MY: Malaysia - PH: Philippines - SG: Singapore - TH: Thailand - US: United States - VN: Vietnam
    */
    'region'?: string;
    /**
    * The SKUs to be synced to the specified market.  **Note**: - You must pass in all existing SKUs. Any existing SKU IDs not listed here will result in the deletion of those SKUs. For example, if this product contains 5 SKUs and you only provide 2 SKU IDs, the remaining 3 will be deleted. - To create new SKUs, leave the SKU ID blank and provide the seller_sku.
    */
    'skus'?: Array<Product202309EditProductRequestBodyReplicatedProductsSkus>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "region",
            "baseName": "region",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202309EditProductRequestBodyReplicatedProductsSkus>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditProductRequestBodyReplicatedProducts.attributeTypeMap;
    }
}

