/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309EditGlobalProductRequestBodyCertificationsFiles } from './EditGlobalProductRequestBodyCertificationsFiles';
import { Product202309EditGlobalProductRequestBodyCertificationsImages } from './EditGlobalProductRequestBodyCertificationsImages';

export class Product202309EditGlobalProductRequestBodyCertifications {
    /**
    * A list of certification related files.
    */
    'files'?: Array<Product202309EditGlobalProductRequestBodyCertificationsFiles>;
    /**
    * The ID to identify the type of certification required for the product category. Retrieve this value from the [Get Global Category Rules API](https://partner.tiktokshop.com/docv2/page/650a056df1fd3102b91b5b8e). 
    */
    'id'?: string;
    /**
    * A list of certification related images.
    */
    'images'?: Array<Product202309EditGlobalProductRequestBodyCertificationsImages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<Product202309EditGlobalProductRequestBodyCertificationsFiles>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202309EditGlobalProductRequestBodyCertificationsImages>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditGlobalProductRequestBodyCertifications.attributeTypeMap;
    }
}

