/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg } from './EditGlobalProductRequestBodySkusSalesAttributesSkuImg';

export class Product202309EditGlobalProductRequestBodySkusSalesAttributes {
    /**
    * The ID of the sales attribute. This is either a built-in sales attribute ID from the [Get Global Attributes API](https://partner.tiktokshop.com/docv2/page/650a0483c16ffe02b8dfc80a) or a custom attribute ID returned after calling [Create Global Product API(https://partner.tiktokshop.com/docv2/page/6509de61bace3e02b7489cba).
    */
    'id'?: string;
    /**
    * A self-defined custom sales attribute name if the built-in attributes do not satisfy your needs. The system will auto-generate an ID after listing.  **Note**:  - Do not include sensitive characters. - Max length: 20 characters
    */
    'name'?: string;
    'skuImg'?: Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg;
    /**
    * The ID of the sales attribute value. This is either a built-in sales attribute value ID from the [Get Global Attributes API](https://partner.tiktokshop.com/docv2/page/650a0483c16ffe02b8dfc80a) or a custom sales attribute value ID returned after calling [Create Global Product API(https://partner.tiktokshop.com/docv2/page/6509de61bace3e02b7489cba).
    */
    'valueId'?: string;
    /**
    * A self-defined custom sales attribute value if the built-in values do not satisfy your needs. The system will auto-generate an ID after listing.  **Note**: - No duplicates allowed under the same attribute. - Max length: 50 characters. - Supports only alphabets and numbers.
    */
    'valueName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "skuImg",
            "baseName": "sku_img",
            "type": "Product202309EditGlobalProductRequestBodySkusSalesAttributesSkuImg"
        },
        {
            "name": "valueId",
            "baseName": "value_id",
            "type": "string"
        },
        {
            "name": "valueName",
            "baseName": "value_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditGlobalProductRequestBodySkusSalesAttributes.attributeTypeMap;
    }
}

