/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309EditGlobalProductRequestBodyProductAttributesValues } from './EditGlobalProductRequestBodyProductAttributesValues';

export class Product202309EditGlobalProductRequestBodyProductAttributes {
    /**
    * The ID of the product attribute, retrieved from the [Get Global Attributes API](https://partner.tiktokshop.com/docv2/page/650a0483c16ffe02b8dfc80a).
    */
    'id'?: string;
    /**
    * A list of selectable values for the product attribute. Max count: 300 for US; 100 for other regions.  **Note**: Provide either a built-in ID or a custom name; if both are provided, the ID takes priority.
    */
    'values'?: Array<Product202309EditGlobalProductRequestBodyProductAttributesValues>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Product202309EditGlobalProductRequestBodyProductAttributesValues>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditGlobalProductRequestBodyProductAttributes.attributeTypeMap;
    }
}

