/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309EditGlobalProductRequestBodyManufacturer {
    /**
    * The address of the manufacturer.
    */
    'address'?: string;
    /**
    * The email address of the manufacturer.
    */
    'email'?: string;
    /**
    * The name of the manufacturer.
    */
    'name'?: string;
    /**
    * The phone number of the manufacturer, prefixed by a plus `+` symbol.  There must be a space or hyphen between the country code and the local phone number.
    */
    'phoneNumber'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309EditGlobalProductRequestBodyManufacturer.attributeTypeMap;
    }
}

