/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202309GetCategoryRulesResponseDataResponsiblePerson {
    /**
    * A flag to indicate whether the responsible person information is required.
    */
    'isRequired'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "isRequired",
            "baseName": "is_required",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetCategoryRulesResponseDataResponsiblePerson.attributeTypeMap;
    }
}

