/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetGlobalProductResponseDataCertificationsFiles } from './GetGlobalProductResponseDataCertificationsFiles';
import { Product202309GetGlobalProductResponseDataCertificationsImages } from './GetGlobalProductResponseDataCertificationsImages';

export class Product202309GetGlobalProductResponseDataCertifications {
    /**
    * A list of certification related files.
    */
    'files'?: Array<Product202309GetGlobalProductResponseDataCertificationsFiles>;
    /**
    * The ID to identify the type of certification required for the product category.
    */
    'id'?: string;
    /**
    * A list of certification related images.
    */
    'images'?: Array<Product202309GetGlobalProductResponseDataCertificationsImages>;
    /**
    * The title of the certification type.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<Product202309GetGlobalProductResponseDataCertificationsFiles>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202309GetGlobalProductResponseDataCertificationsImages>"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetGlobalProductResponseDataCertifications.attributeTypeMap;
    }
}

