/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetGlobalProductResponseDataBrand } from './GetGlobalProductResponseDataBrand';
import { Product202309GetGlobalProductResponseDataCategory } from './GetGlobalProductResponseDataCategory';
import { Product202309GetGlobalProductResponseDataCertifications } from './GetGlobalProductResponseDataCertifications';
import { Product202309GetGlobalProductResponseDataMainImages } from './GetGlobalProductResponseDataMainImages';
import { Product202309GetGlobalProductResponseDataManufacturer } from './GetGlobalProductResponseDataManufacturer';
import { Product202309GetGlobalProductResponseDataPackageDimensions } from './GetGlobalProductResponseDataPackageDimensions';
import { Product202309GetGlobalProductResponseDataPackageWeight } from './GetGlobalProductResponseDataPackageWeight';
import { Product202309GetGlobalProductResponseDataProductAttributes } from './GetGlobalProductResponseDataProductAttributes';
import { Product202309GetGlobalProductResponseDataProducts } from './GetGlobalProductResponseDataProducts';
import { Product202309GetGlobalProductResponseDataSizeChart } from './GetGlobalProductResponseDataSizeChart';
import { Product202309GetGlobalProductResponseDataSkus } from './GetGlobalProductResponseDataSkus';
import { Product202309GetGlobalProductResponseDataVideo } from './GetGlobalProductResponseDataVideo';

export class Product202309GetGlobalProductResponseData {
    'brand'?: Product202309GetGlobalProductResponseDataBrand;
    'category'?: Product202309GetGlobalProductResponseDataCategory;
    /**
    * The list of certifications for your product.
    */
    'certifications'?: Array<Product202309GetGlobalProductResponseDataCertifications>;
    /**
    * The time when the product is created. Unix timestamp.
    */
    'createTime'?: number;
    /**
    * The product description in HTML format.
    */
    'description'?: string;
    /**
    * An external identifier used in an external ecommerce platform. This is used to associate the product between TikTok Shop and the external ecommerce platform.
    */
    'externalGlobalProductId'?: string;
    /**
    * The cross-border seller ID.
    */
    'globalSellerId'?: string;
    /**
    * The global product ID in TikTok Shop.
    */
    'id'?: string;
    /**
    * A list of images to display in the product image gallery.
    */
    'mainImages'?: Array<Product202309GetGlobalProductResponseDataMainImages>;
    'manufacturer'?: Product202309GetGlobalProductResponseDataManufacturer;
    /**
    * A comma-delimited list of manufacturer IDs. Retrieve the IDs from the [Search Manufacturers API](67066a580dcee902fa03ccf9). **Note**: Applicable only for the EU market in certain categories.
    */
    'manufacturerIds'?: Array<string>;
    'packageDimensions'?: Product202309GetGlobalProductResponseDataPackageDimensions;
    'packageWeight'?: Product202309GetGlobalProductResponseDataPackageWeight;
    /**
    * A list of general attributes (e.g. manufacturer, country of origin, materials used) that describe the product as a whole, regardless of variant.
    */
    'productAttributes'?: Array<Product202309GetGlobalProductResponseDataProductAttributes>;
    /**
    * The local products associated through global product publishing or manual binding.
    */
    'products'?: Array<Product202309GetGlobalProductResponseDataProducts>;
    /**
    * A comma-delimited list of responsible person IDs. Retrieve the IDs from the [Search Responsible Persons API](67066a55f17b7d02f95d2fb1). **Note**: Applicable only for the EU market in certain categories.
    */
    'responsiblePersonIds'?: Array<string>;
    'sizeChart'?: Product202309GetGlobalProductResponseDataSizeChart;
    /**
    * A list of global Stock Keeping Units (SKUs) used to identify distinct variants of the product.
    */
    'skus'?: Array<Product202309GetGlobalProductResponseDataSkus>;
    /**
    * The BCP-47 locale code representing the source language used for specifying the product information. Default: en-US Possible values: - de-DE - en-IE - es-ES - fr-FR - it-IT  **Note**: Applicable only for intra-EU sellers.
    */
    'sourceLocale'?: string;
    /**
    * The product title. 
    */
    'title'?: string;
    /**
    * The time when the product is last updated. Unix timestamp.
    */
    'updateTime'?: number;
    'video'?: Product202309GetGlobalProductResponseDataVideo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "brand",
            "baseName": "brand",
            "type": "Product202309GetGlobalProductResponseDataBrand"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "Product202309GetGlobalProductResponseDataCategory"
        },
        {
            "name": "certifications",
            "baseName": "certifications",
            "type": "Array<Product202309GetGlobalProductResponseDataCertifications>"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "externalGlobalProductId",
            "baseName": "external_global_product_id",
            "type": "string"
        },
        {
            "name": "globalSellerId",
            "baseName": "global_seller_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "mainImages",
            "baseName": "main_images",
            "type": "Array<Product202309GetGlobalProductResponseDataMainImages>"
        },
        {
            "name": "manufacturer",
            "baseName": "manufacturer",
            "type": "Product202309GetGlobalProductResponseDataManufacturer"
        },
        {
            "name": "manufacturerIds",
            "baseName": "manufacturer_ids",
            "type": "Array<string>"
        },
        {
            "name": "packageDimensions",
            "baseName": "package_dimensions",
            "type": "Product202309GetGlobalProductResponseDataPackageDimensions"
        },
        {
            "name": "packageWeight",
            "baseName": "package_weight",
            "type": "Product202309GetGlobalProductResponseDataPackageWeight"
        },
        {
            "name": "productAttributes",
            "baseName": "product_attributes",
            "type": "Array<Product202309GetGlobalProductResponseDataProductAttributes>"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202309GetGlobalProductResponseDataProducts>"
        },
        {
            "name": "responsiblePersonIds",
            "baseName": "responsible_person_ids",
            "type": "Array<string>"
        },
        {
            "name": "sizeChart",
            "baseName": "size_chart",
            "type": "Product202309GetGlobalProductResponseDataSizeChart"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202309GetGlobalProductResponseDataSkus>"
        },
        {
            "name": "sourceLocale",
            "baseName": "source_locale",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "Product202309GetGlobalProductResponseDataVideo"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetGlobalProductResponseData.attributeTypeMap;
    }
}

