/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309GetProductResponseDataCertificationsFiles } from './GetProductResponseDataCertificationsFiles';
import { Product202309GetProductResponseDataCertificationsImages } from './GetProductResponseDataCertificationsImages';

export class Product202309GetProductResponseDataCertifications {
    /**
    * The expiration date of this certification expressed in unix timestamp (seconds) UTC+0.
    */
    'expirationDate'?: number;
    /**
    * A list of certification related files.
    */
    'files'?: Array<Product202309GetProductResponseDataCertificationsFiles>;
    /**
    * The ID to identify the type of certification required for the product.
    */
    'id'?: string;
    /**
    * A list of certification related images.
    */
    'images'?: Array<Product202309GetProductResponseDataCertificationsImages>;
    /**
    * The title of the certification type.
    */
    'title'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "number"
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<Product202309GetProductResponseDataCertificationsFiles>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202309GetProductResponseDataCertificationsImages>"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202309GetProductResponseDataCertifications.attributeTypeMap;
    }
}

