/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202309InventorySearchResponseDataInventory } from './InventorySearchResponseDataInventory';

export class Product202309InventorySearchResponseData {
    /**
    * Inventory information for the requested products or SKUs.
    */
    'inventory'?: Array<Product202309InventorySearchResponseDataInventory>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202309InventorySearchResponseDataInventory>"
        }    ];

    static getAttributeTypeMap() {
        return Product202309InventorySearchResponseData.attributeTypeMap;
    }
}

