/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202309SearchActivitiesRequestBody {
    /**
    * Activity title key words. No fuzzy matching.
    */
    'activityTitle'?: string;
    /**
    * The type of activities. If `activity_type`  isn\'t passed, return activities of all types. Possible values: The type of activities. Possible values: - `FIXED_PRICE` - `DIRECT_DISCOUNT` - `FLASHSALE` - `SHIPPING_DISCOUNT` - `BUY_MORE_SAVE_MORE`
    */
    'activityType'?: string;
    /**
    * Page size. The range is `[0, 100]`. `50` by default.
    */
    'pageSize'?: number;
    /**
    * Specify the value for the page. Use `\"\"` for the first page.
    */
    'pageToken'?: string;
    /**
    * Activity status. Possible values: - DRAFT: Promotion activities with this status are not available to TikTok users. - NOT_START: Promotion activities with this status are not available to TikTok users until the set activity start time. - ONGOING: Promotion activities with this status are available to TikTok users. - EXPIRED: Promotion activities with this status are not available to TikTok users because it has expired. - DEACTIVATED: The activity has been deactivated by the seller and is not available to TikTok users. - NOT_EFFECTIVE:  The activity is terminated by the platform and is not available to TikTok users.
    */
    'status'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activityTitle",
            "baseName": "activity_title",
            "type": "string"
        },
        {
            "name": "activityType",
            "baseName": "activity_type",
            "type": "string"
        },
        {
            "name": "pageSize",
            "baseName": "page_size",
            "type": "number"
        },
        {
            "name": "pageToken",
            "baseName": "page_token",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309SearchActivitiesRequestBody.attributeTypeMap;
    }
}

