/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202501SearchManufacturersResponseDataManufacturers } from './SearchManufacturersResponseDataManufacturers';

export class Product202501SearchManufacturersResponseData {
    /**
    * The list of manufacturers that meet the query conditions.
    */
    'manufacturers'?: Array<Product202501SearchManufacturersResponseDataManufacturers>;
    /**
    * An opaque token used to retrieve the next page of a paginated result set. Provide this value in the `page_token` parameter of your request if the current response does not return all the results.
    */
    'nextPageToken'?: string;
    /**
    * The number of manufacturers that meet the query conditions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "manufacturers",
            "baseName": "manufacturers",
            "type": "Array<Product202501SearchManufacturersResponseDataManufacturers>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Product202501SearchManufacturersResponseData.attributeTypeMap;
    }
}

