/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Fulfillment202512CreatePackagesResponseDataDimension } from './CreatePackagesResponseDataDimension';
import { Fulfillment202512CreatePackagesResponseDataShippingServiceInfo } from './CreatePackagesResponseDataShippingServiceInfo';
import { Fulfillment202512CreatePackagesResponseDataWeight } from './CreatePackagesResponseDataWeight';

export class Fulfillment202512CreatePackagesResponseData {
    /**
    * The time when the product was created. Unix timestamp.
    */
    'createTime'?: number;
    'dimension'?: Fulfillment202512CreatePackagesResponseDataDimension;
    /**
    * Package ID.
    */
    'packageId'?: string;
    'shippingServiceInfo'?: Fulfillment202512CreatePackagesResponseDataShippingServiceInfo;
    'weight'?: Fulfillment202512CreatePackagesResponseDataWeight;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "dimension",
            "baseName": "dimension",
            "type": "Fulfillment202512CreatePackagesResponseDataDimension"
        },
        {
            "name": "packageId",
            "baseName": "package_id",
            "type": "string"
        },
        {
            "name": "shippingServiceInfo",
            "baseName": "shipping_service_info",
            "type": "Fulfillment202512CreatePackagesResponseDataShippingServiceInfo"
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "Fulfillment202512CreatePackagesResponseDataWeight"
        }    ];

    static getAttributeTypeMap() {
        return Fulfillment202512CreatePackagesResponseData.attributeTypeMap;
    }
}

