/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202507GetGlobalReplicatedProductsResponseDataReplicatedProducts } from './GetGlobalReplicatedProductsResponseDataReplicatedProducts';

export class Product202507GetGlobalReplicatedProductsResponseData {
    /**
    * The globally associated replicas in other markets if the product has been replicated through local replication.
    */
    'replicatedProducts'?: Array<Product202507GetGlobalReplicatedProductsResponseDataReplicatedProducts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "replicatedProducts",
            "baseName": "replicated_products",
            "type": "Array<Product202507GetGlobalReplicatedProductsResponseDataReplicatedProducts>"
        }    ];

    static getAttributeTypeMap() {
        return Product202507GetGlobalReplicatedProductsResponseData.attributeTypeMap;
    }
}

