/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202507ReplicateProductRequestBodyReplicateTarget } from './ReplicateProductRequestBodyReplicateTarget';

export class Product202507ReplicateProductRequestBody {
    /**
    * Target markets for replicating the local product.
    */
    'replicateTarget'?: Array<Product202507ReplicateProductRequestBodyReplicateTarget>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "replicateTarget",
            "baseName": "replicate_target",
            "type": "Array<Product202507ReplicateProductRequestBodyReplicateTarget>"
        }    ];

    static getAttributeTypeMap() {
        return Product202507ReplicateProductRequestBody.attributeTypeMap;
    }
}

