/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202404OptimizedImagesRequestBodyImages } from './OptimizedImagesRequestBodyImages';

export class Product202404OptimizedImagesRequestBody {
    /**
    * The list of images to be optimized.  Use the [Upload Product Image API](https://partner.tiktokshop.com/docv2/page/6509df95defece02be598a22) to upload the images first and obtain the corresponding image URIs. Max count: 200
    */
    'images'?: Array<Product202404OptimizedImagesRequestBodyImages>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "images",
            "baseName": "images",
            "type": "Array<Product202404OptimizedImagesRequestBodyImages>"
        }    ];

    static getAttributeTypeMap() {
        return Product202404OptimizedImagesRequestBody.attributeTypeMap;
    }
}

