/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202309CreateConversationRequestBody {
    /**
    * Buyer\'s user ID The value is the same as `data.orders.user_id` in the response data of [Get Order Detail](650aa8ccc16ffe02b8f167a0).
    */
    'buyerUserId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buyerUserId",
            "baseName": "buyer_user_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202309CreateConversationRequestBody.attributeTypeMap;
    }
}

