/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class CustomerService202407GetCustomerServicePerformanceResponseDataPerformance {
    /**
    * The percentage of chat support sessions of which the first response happens within 24 hours. The sessions which started in the specified time slot are included in calculation. - Automated responses such as FAQ cards are regarded as responses within 24 hours. - Sessions initiated during vacation mode are excluded from this calculation.
    */
    'responsePercentage'?: string;
    /**
    * The average first response time in minutes for chat support sessions. The sessions which started in the specified time slot are included in calculation.
    */
    'responseTimeMins'?: string;
    /**
    * The percentage of chat support sessions rated \'Satisfied\' (4 or 5 stars). The sessions of which the rating occurred in the specified time slot are included in the calculation; the sessions without rate are not included in the calculation.
    */
    'satisfactionPercentage'?: string;
    /**
    * The total number of chat support sessions initiated by customers. A session starts when a customer first clicks an FAQ card or sends a message (text, image, video, emoji, product card, order card, etc.) in chat. The sessions which started in the specified time slot are included in calculation.
    */
    'supportSessionCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "responsePercentage",
            "baseName": "response_percentage",
            "type": "string"
        },
        {
            "name": "responseTimeMins",
            "baseName": "response_time_mins",
            "type": "string"
        },
        {
            "name": "satisfactionPercentage",
            "baseName": "satisfaction_percentage",
            "type": "string"
        },
        {
            "name": "supportSessionCount",
            "baseName": "support_session_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CustomerService202407GetCustomerServicePerformanceResponseDataPerformance.attributeTypeMap;
    }
}

