/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility {
    /**
    * Use this field to recognize whether an item is eligible for an aftersale request: - TRUE - FALSE
    */
    'eligible'?: boolean;
    /**
    * The reason code for an ineligible aftersale request.
    */
    'ineligibleCode'?: number;
    /**
    * The reason for an ineligible aftersale request.
    */
    'ineligibleReason'?: string;
    /**
    * IDs of order line items.
    */
    'orderLineItemsIds'?: Array<string>;
    /**
    * Aftersale request type. Possible values: - CANCEL - RETURN - RETURN_AND_REFUND
    */
    'requestType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eligible",
            "baseName": "eligible",
            "type": "boolean"
        },
        {
            "name": "ineligibleCode",
            "baseName": "ineligible_code",
            "type": "number"
        },
        {
            "name": "ineligibleReason",
            "baseName": "ineligible_reason",
            "type": "string"
        },
        {
            "name": "orderLineItemsIds",
            "baseName": "order_line_items_ids",
            "type": "Array<string>"
        },
        {
            "name": "requestType",
            "baseName": "request_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility.attributeTypeMap;
    }
}

