/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnWarehouseAddress {
    /**
    * The full return warehouse address.
    */
    'fullAddress'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fullAddress",
            "baseName": "full_address",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309SearchReturnsResponseDataReturnOrdersReturnWarehouseAddress.attributeTypeMap;
    }
}

