/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsProductImage } from './SearchCancellationsResponseDataCancellationsCancelLineItemsProductImage';
import { ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount } from './SearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount';

export class ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItems {
    /**
    * Cancellation line item ID.
    */
    'cancelLineItemId'?: string;
    /**
    * Order line item ID.
    */
    'orderLineItemId'?: string;
    'productImage'?: ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsProductImage;
    /**
    * Product name.
    */
    'productName'?: string;
    'refundAmount'?: ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount;
    /**
    * SKU name defined by the seller.
    */
    'sellerSku'?: string;
    /**
    * SKU ID.
    */
    'skuId'?: string;
    /**
    * SKU name.
    */
    'skuName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelLineItemId",
            "baseName": "cancel_line_item_id",
            "type": "string"
        },
        {
            "name": "orderLineItemId",
            "baseName": "order_line_item_id",
            "type": "string"
        },
        {
            "name": "productImage",
            "baseName": "product_image",
            "type": "ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsProductImage"
        },
        {
            "name": "productName",
            "baseName": "product_name",
            "type": "string"
        },
        {
            "name": "refundAmount",
            "baseName": "refund_amount",
            "type": "ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItemsRefundAmount"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        },
        {
            "name": "skuName",
            "baseName": "sku_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309SearchCancellationsResponseDataCancellationsCancelLineItems.attributeTypeMap;
    }
}

