/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount {
    /**
    * The discount currency.
    */
    'currency'?: string;
    /**
    * The refund amount of platform discount.
    */
    'productPlatformDiscount'?: string;
    /**
    * The refund amount of product seller discount.
    */
    'productSellerDiscount'?: string;
    /**
    * The refund amount of shipping fee platform discount.
    */
    'shippingFeePlatformDiscount'?: string;
    /**
    * The refund amount of shipping fee seller discount.
    */
    'shippingFeeSellerDiscount'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "productPlatformDiscount",
            "baseName": "product_platform_discount",
            "type": "string"
        },
        {
            "name": "productSellerDiscount",
            "baseName": "product_seller_discount",
            "type": "string"
        },
        {
            "name": "shippingFeePlatformDiscount",
            "baseName": "shipping_fee_platform_discount",
            "type": "string"
        },
        {
            "name": "shippingFeeSellerDiscount",
            "baseName": "shipping_fee_seller_discount",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309SearchReturnsResponseDataReturnOrdersDiscountAmount.attributeTypeMap;
    }
}

