/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202309SearchCancellationsResponseDataCancellations } from './SearchCancellationsResponseDataCancellations';

export class ReturnRefund202309SearchCancellationsResponseData {
    /**
    * List of order cancellations.
    */
    'cancellations'?: Array<ReturnRefund202309SearchCancellationsResponseDataCancellations>;
    /**
    * An opaque token used to retrieve the next page of a paginated result set. Provide this value in the page_token parameter of your request if the current response does not return all the results.
    */
    'nextPageToken'?: string;
    /**
    * The number of cancellations that meet the query conditions.
    */
    'totalCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancellations",
            "baseName": "cancellations",
            "type": "Array<ReturnRefund202309SearchCancellationsResponseDataCancellations>"
        },
        {
            "name": "nextPageToken",
            "baseName": "next_page_token",
            "type": "string"
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202309SearchCancellationsResponseData.attributeTypeMap;
    }
}

