/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesDiagnosisResults {
    /**
    * A machine-readable code that represents an identified issue. Refer to [Listing quality diagnosis](https://partner.tiktokshop.com/docv2/page/66eb8f5c6f2da702e96a49dd) for the full list of diagnosed issues and the corresponding recommendations.
    */
    'code'?: string;
    /**
    * The recommendation for resolving the identified issue, returned in the default locale language of the shop. Refer to [Listing quality diagnosis](https://partner.tiktokshop.com/docv2/page/66eb8f5c6f2da702e96a49dd) for the full list of recommendations.
    */
    'howToSolve'?: string;
    /**
    * The listing quality tier you can reach by implementing the recommendation. Possible values: - FAIR - GOOD  **Note**:  - To reach a higher tier, you must implement all recommendations from the destination tier and all preceding tiers. For example, a product will reach the \"GOOD\" tier once all \"FAIR\" and \"GOOD\" recommendations are addressed or implemented. - Available only for the US market.
    */
    'qualityTier'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "howToSolve",
            "baseName": "how_to_solve",
            "type": "string"
        },
        {
            "name": "qualityTier",
            "baseName": "quality_tier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202405ProductInformationIssueDiagnosisResponseDataProductsDiagnosesDiagnosisResults.attributeTypeMap;
    }
}

