/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509EditProductRequestBodyReplicatedProductsSkusInventory } from './EditProductRequestBodyReplicatedProductsSkusInventory';
import { Product202509EditProductRequestBodyReplicatedProductsSkusPrice } from './EditProductRequestBodyReplicatedProductsSkusPrice';

export class Product202509EditProductRequestBodyReplicatedProductsSkus {
    /**
    * The SKU ID generated by TikTok Shop. Provide this for existing SKUs.
    */
    'id'?: string;
    /**
    * SKU inventory information per warehouse.
    */
    'inventory'?: Array<Product202509EditProductRequestBodyReplicatedProductsSkusInventory>;
    'price'?: Product202509EditProductRequestBodyReplicatedProductsSkusPrice;
    /**
    * The seller_sku value of the source product above. Provide this for new SKUs. - Valid length: 1-50 characters - Format: Text without spaces
    */
    'sellerSku'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inventory",
            "baseName": "inventory",
            "type": "Array<Product202509EditProductRequestBodyReplicatedProductsSkusInventory>"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "Product202509EditProductRequestBodyReplicatedProductsSkusPrice"
        },
        {
            "name": "sellerSku",
            "baseName": "seller_sku",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202509EditProductRequestBodyReplicatedProductsSkus.attributeTypeMap;
    }
}

