/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202502SearchProductsResponseDataProductsProductFamiliesProducts } from './SearchProductsResponseDataProductsProductFamiliesProducts';

export class Product202502SearchProductsResponseDataProductsProductFamilies {
    /**
    * The product family ID.
    */
    'id'?: string;
    /**
    * A list of products that belong to the family.
    */
    'products'?: Array<Product202502SearchProductsResponseDataProductsProductFamiliesProducts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Product202502SearchProductsResponseDataProductsProductFamiliesProducts>"
        }    ];

    static getAttributeTypeMap() {
        return Product202502SearchProductsResponseDataProductsProductFamilies.attributeTypeMap;
    }
}

