/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202406GetCouponResponseDataCouponLiveTasks {
    /**
    * Number of seconds for which the shopper must watch the LIVE in order to claim the coupon.
    */
    'minWatchTime'?: string;
    /**
    * Possible enumerations: - `NONE`: Any shopper in the LIVE room may claim the coupon. - `FOLLOW_HOST`: Shoppers must follow the LIVE host before being able to claim the coupon. - `WATCH_FOR_MIN_TIME`: Shoppers must watch the LIVE for the time specified by `min_watch_time` before being able to claim the coupon.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "minWatchTime",
            "baseName": "min_watch_time",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202406GetCouponResponseDataCouponLiveTasks.attributeTypeMap;
    }
}

