/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202406SearchCouponsResponseDataCouponsRedemptionDuration {
    /**
    * The UNIX timestamp at which the redemption period ends, if `type == \'ABSOLUTE\'`.
    */
    'endTime'?: number;
    /**
    * The number of days after coupon claim time for which a coupon is valid to be redeemed, `type = \'RELATIVE\'`.
    */
    'relativeTime'?: number;
    /**
    * The UNIX timestamp at which the redemption period starts, if `type == \'ABSOLUTE\'`.
    */
    'startTime'?: number;
    /**
    * Values: - `ABSOLUTE`: the redemption period starts from `start_time` and ends at `end_time`. - `RELATIVE`: the redemption period starts from the time the coupon is claimed and lasts for `relative_time`.
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "relativeTime",
            "baseName": "relative_time",
            "type": "number"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202406SearchCouponsResponseDataCouponsRedemptionDuration.attributeTypeMap;
    }
}

