/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplates } from './GetAvailableShippingTemplateResponseDataTemplates';

export class Logistics202510GetAvailableShippingTemplateResponseData {
    /**
    * All the seller\'s template
    */
    'templates'?: Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplates>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "templates",
            "baseName": "templates",
            "type": "Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplates>"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseData.attributeTypeMap;
    }
}

