/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202509EditProductResponseDataAudit } from './EditProductResponseDataAudit';
import { Product202509EditProductResponseDataSkus } from './EditProductResponseDataSkus';
import { Product202509EditProductResponseDataWarnings } from './EditProductResponseDataWarnings';

export class Product202509EditProductResponseData {
    'audit'?: Product202509EditProductResponseDataAudit;
    /**
    * The product ID generated by TikTok Shop.
    */
    'productId'?: string;
    /**
    * A list of Stock Keeping Units (SKUs) used to identify distinct variants of the product.
    */
    'skus'?: Array<Product202509EditProductResponseDataSkus>;
    /**
    * Warning information that the API caller needs to pay special attention to.
    */
    'warnings'?: Array<Product202509EditProductResponseDataWarnings>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "audit",
            "baseName": "audit",
            "type": "Product202509EditProductResponseDataAudit"
        },
        {
            "name": "productId",
            "baseName": "product_id",
            "type": "string"
        },
        {
            "name": "skus",
            "baseName": "skus",
            "type": "Array<Product202509EditProductResponseDataSkus>"
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<Product202509EditProductResponseDataWarnings>"
        }    ];

    static getAttributeTypeMap() {
        return Product202509EditProductResponseData.attributeTypeMap;
    }
}

