/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202411DiagnoseandOptimizeProductRequestBodySizeChartImage } from './DiagnoseandOptimizeProductRequestBodySizeChartImage';
import { Product202411DiagnoseandOptimizeProductRequestBodySizeChartTemplate } from './DiagnoseandOptimizeProductRequestBodySizeChartTemplate';

export class Product202411DiagnoseandOptimizeProductRequestBodySizeChart {
    'image'?: Product202411DiagnoseandOptimizeProductRequestBodySizeChartImage;
    'template'?: Product202411DiagnoseandOptimizeProductRequestBodySizeChartTemplate;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "image",
            "baseName": "image",
            "type": "Product202411DiagnoseandOptimizeProductRequestBodySizeChartImage"
        },
        {
            "name": "template",
            "baseName": "template",
            "type": "Product202411DiagnoseandOptimizeProductRequestBodySizeChartTemplate"
        }    ];

    static getAttributeTypeMap() {
        return Product202411DiagnoseandOptimizeProductRequestBodySizeChart.attributeTypeMap;
    }
}

