/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202506GetImageTranslationTasksResponseDataTranslationTasksOriginalImage } from './GetImageTranslationTasksResponseDataTranslationTasksOriginalImage';
import { Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage } from './GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage';

export class Product202506GetImageTranslationTasksResponseDataTranslationTasks {
    /**
    * The reason why the translation task failed. Possible values: - Invalid image URI. - Internal processing error, please try calling this endpoint again. - This image can\'t be translated. Try a different image.
    */
    'failReason'?: string;
    /**
    * The ID to identify the image translation task.
    */
    'id'?: string;
    'originalImage'?: Product202506GetImageTranslationTasksResponseDataTranslationTasksOriginalImage;
    /**
    * The translation result. Possible values: - PROCESSING: Translation is underway and has not yet completed. - COMPLETED: Translation has completed and results are ready. - FAILED: Translation did not complete due to an error.
    */
    'status'?: string;
    /**
    * The target language to translate the image into. Possible values: - de-DE - en-IE - es-ES - fr-FR - it-IT
    */
    'targetLanguage'?: string;
    'translatedImage'?: Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "failReason",
            "baseName": "fail_reason",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "originalImage",
            "baseName": "original_image",
            "type": "Product202506GetImageTranslationTasksResponseDataTranslationTasksOriginalImage"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "targetLanguage",
            "baseName": "target_language",
            "type": "string"
        },
        {
            "name": "translatedImage",
            "baseName": "translated_image",
            "type": "Product202506GetImageTranslationTasksResponseDataTranslationTasksTranslatedImage"
        }    ];

    static getAttributeTypeMap() {
        return Product202506GetImageTranslationTasksResponseDataTranslationTasks.attributeTypeMap;
    }
}

