/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202409PartialEditResponsiblePersonRequestBodyAddress {
    /**
    * (**Deprecated**: This field is deprecated and will be removed in a future API version. If provided, its value will be merged into `street_address_line1`. It is recommended to specify `street_address_line1` directly.) The city name. Max length: 500 characters
    */
    'city'?: string;
    /**
    * The two letter ISO 3166 country code representing the country of the address. It must be an EU country.
    */
    'country'?: string;
    /**
    * (**Deprecated**: This field is deprecated and will be removed in a future API version. If provided, its value will be merged into `street_address_line1`. It is recommended to specify `street_address_line1` directly.) The district name. Max length: 500 characters
    */
    'district'?: string;
    /**
    * The postal code. Max length: 500 characters
    */
    'postalCode'?: string;
    /**
    * (**Deprecated**: This field is deprecated and will be removed in a future API version. If provided, its value will be merged into `street_address_line1`. It is recommended to specify `street_address_line1` directly.) The province, state, or region name. Max length: 500 characters
    */
    'province'?: string;
    /**
    * The detailed street address of the location, including the building number, street name, district, city, province, and any relevant details. Max length: 500 characters
    */
    'streetAddressLine1'?: string;
    /**
    * (**Deprecated**: This field is deprecated and will be removed in a future API version. If provided, its value will be merged into `street_address_line1`. It is recommended to specify `street_address_line1` directly.) An optional secondary line for additional address details, if necessary. Max length: 500 characters
    */
    'streetAddressLine2'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "district",
            "baseName": "district",
            "type": "string"
        },
        {
            "name": "postalCode",
            "baseName": "postal_code",
            "type": "string"
        },
        {
            "name": "province",
            "baseName": "province",
            "type": "string"
        },
        {
            "name": "streetAddressLine1",
            "baseName": "street_address_line1",
            "type": "string"
        },
        {
            "name": "streetAddressLine2",
            "baseName": "street_address_line2",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Product202409PartialEditResponsiblePersonRequestBodyAddress.attributeTypeMap;
    }
}

