/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason } from './GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason';

export class Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason {
    /**
    * Contains the reason why this template is not usable
    */
    'filterReason'?: Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason>;
    /**
    * Id of the service
    */
    'serviceId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterReason",
            "baseName": "filter_reason",
            "type": "Array<Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReasonFilterReason>"
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Logistics202510GetAvailableShippingTemplateResponseDataTemplatesServiceUnreachableReason.attributeTypeMap;
    }
}

