/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Product202501SearchResponsiblePersonsRequestBody {
    /**
    * Filter results to show those that contain this keyword. Search scope: name, local_number, email Max length: 200 characters  **Note**: Provide either the `responsible_person_ids` or `keyword`; if both are provided, `responsible_person_ids` will take priority.
    */
    'keyword'?: string;
    /**
    * The BCP-47 locale codes for displaying the responsible person information. Default: The locale of the seller\'s registered business address. Possible values: - de-DE - en-IE - es-ES - fr-FR - it-IT
    */
    'locales'?: Array<string>;
    /**
    * Filter results by these responsible person IDs. Max IDs: The value of `page_size`
    */
    'responsiblePersonIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keyword",
            "baseName": "keyword",
            "type": "string"
        },
        {
            "name": "locales",
            "baseName": "locales",
            "type": "Array<string>"
        },
        {
            "name": "responsiblePersonIds",
            "baseName": "responsible_person_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Product202501SearchResponsiblePersonsRequestBody.attributeTypeMap;
    }
}

