/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202309GetActivityResponseDataDiscount } from './GetActivityResponseDataDiscount';
import { Promotion202309GetActivityResponseDataParticipationLimit } from './GetActivityResponseDataParticipationLimit';
import { Promotion202309GetActivityResponseDataProducts } from './GetActivityResponseDataProducts';

export class Promotion202309GetActivityResponseData {
    /**
    * Applicable commands to the activity: - IMMUTABLE: The activity cann\'t be editable or deactivated
    */
    'activityCommands'?: Array<string>;
    /**
    * A unique ID that identifies different activities.
    */
    'activityId'?: string;
    /**
    * The type of activities. Possible enumerations: - `FIXED_PRICE`: product discount activity with fixed price. - `DIRECT_DISCOUNT`: product discount activities with percentage off. - `FLASHSALE`: flash sale activity. - `SHIPPING_DISCOUNT`: shipping fee discount. - `BUY_MORE_SAVE_MORE`: Buy more save more discount.
    */
    'activityType'?: string;
    /**
    * Activity start time. UNIX timestamp. The value must be greater than the value of the current time.
    */
    'beginTime'?: number;
    /**
    * Activity creation time. UNIX timestamp.
    */
    'createTime'?: number;
    'discount'?: Promotion202309GetActivityResponseDataDiscount;
    /**
    * The effective time type of the current activity - NORMAL:  `begin_time` and `end_time` must be filled - INDEFINITE: `begin_time` and `end_time` aren\'t required, and the promotion will be a long-term activity which runs indefinitely.  1.  `INDEFINITE` is only valid when `activity_type` is `SHIPPING_DISCOUNT`, 2. If `duration_type` is `INDEFINITE`, `start_time` and `end_time` should be 0 Default: NORMAL
    */
    'durationType'?: string;
    /**
    * Activity end time. UNIX timestamp.
    */
    'endTime'?: number;
    /**
    * The number of times a buyer can participate in the promotion.
    */
    'participationLimit'?: Array<Promotion202309GetActivityResponseDataParticipationLimit>;
    /**
    * Activity product dimension, values are:  - PRODUCT: Product level promotion activity. - VARIATION: SKU level promotion activity. - SHOP: Shop level promotion activity.
    */
    'productLevel'?: string;
    /**
    * Product List. Note:If  `FIXED_PRICE`, `DIRECT_DISCOUNT` and `FLASHSALE` activity that ended more than 180 days,this field is empty.
    */
    'products'?: Array<Promotion202309GetActivityResponseDataProducts>;
    /**
    * Activity status. Possible values: - DRAFT: Promotion activities with this status are not available to TikTok users. - NOT_START: Promotion activities with this status are not available to TikTok users until the set activity start time. - ONGOING: Promotion activities with this status are available to TikTok users. - EXPIRED: Promotion activities with this status are not available to TikTok users because it has expired. - DEACTIVATED: The activity has been deactivated by the seller and is not available to TikTok users. - NOT_EFFECTIVE:  The activity is terminated by the platform and is not available to TikTok users.
    */
    'status'?: string;
    /**
    * Activity name (50 characters max.) The name must be unique.
    */
    'title'?: string;
    /**
    * Activity update time. UNIX timestamp.
    */
    'updateTime'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activityCommands",
            "baseName": "activity_commands",
            "type": "Array<string>"
        },
        {
            "name": "activityId",
            "baseName": "activity_id",
            "type": "string"
        },
        {
            "name": "activityType",
            "baseName": "activity_type",
            "type": "string"
        },
        {
            "name": "beginTime",
            "baseName": "begin_time",
            "type": "number"
        },
        {
            "name": "createTime",
            "baseName": "create_time",
            "type": "number"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "Promotion202309GetActivityResponseDataDiscount"
        },
        {
            "name": "durationType",
            "baseName": "duration_type",
            "type": "string"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number"
        },
        {
            "name": "participationLimit",
            "baseName": "participation_limit",
            "type": "Array<Promotion202309GetActivityResponseDataParticipationLimit>"
        },
        {
            "name": "productLevel",
            "baseName": "product_level",
            "type": "string"
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<Promotion202309GetActivityResponseDataProducts>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "update_time",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309GetActivityResponseData.attributeTypeMap;
    }
}

