/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';

export class Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscountAreaScope {
    /**
    * The list of areas for which the promotion activity applies. The valid values that may be included in this list are dependent on the region of the shop. The list of valid values for each shop region are available here: [link](https://partner.tiktokshop.com/docv2/page/67e3b059e7dc4f04a4ff9e09)
    */
    'specificAreas'?: Array<string>;
    /**
    * The (buyer\'s) geographical area to which the promotion activity applies. ​- `WHOLE`: Promotion activity applies to all areas to which the seller offers fulfillment.  - `SPECIFIC_AREAS`: Only applies to specific fulfillment areas, as defined in `area_scope.specific_areas`
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "specificAreas",
            "baseName": "specific_areas",
            "type": "Array<string>"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscountAreaScope.attributeTypeMap;
    }
}

