/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscount } from './SearchActivitiesResponseDataActivitiesDiscountBmsmDiscount';
import { Promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount } from './SearchActivitiesResponseDataActivitiesDiscountGiftDiscount';
import { Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount } from './SearchActivitiesResponseDataActivitiesDiscountShippingDiscount';

export class Promotion202309SearchActivitiesResponseDataActivitiesDiscount {
    'bmsmDiscount'?: Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscount;
    'giftDiscount'?: Promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount;
    'shippingDiscount'?: Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bmsmDiscount",
            "baseName": "bmsm_discount",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountBmsmDiscount"
        },
        {
            "name": "giftDiscount",
            "baseName": "gift_discount",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountGiftDiscount"
        },
        {
            "name": "shippingDiscount",
            "baseName": "shipping_discount",
            "type": "Promotion202309SearchActivitiesResponseDataActivitiesDiscountShippingDiscount"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202309SearchActivitiesResponseDataActivitiesDiscount.attributeTypeMap;
    }
}

