/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202512GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility } from './GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility';

export class ReturnRefund202512GetAftersaleEligibilityResponseDataSkuEligibility {
    /**
    * The eligible aftersale options based on order line item.
    */
    'lineItemEligibility'?: Array<ReturnRefund202512GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility>;
    /**
    * SKU ID.
    */
    'skuId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lineItemEligibility",
            "baseName": "line_item_eligibility",
            "type": "Array<ReturnRefund202512GetAftersaleEligibilityResponseDataSkuEligibilityLineItemEligibility>"
        },
        {
            "name": "skuId",
            "baseName": "sku_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202512GetAftersaleEligibilityResponseDataSkuEligibility.attributeTypeMap;
    }
}

