/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems } from './GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems';

export class Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions {
    /**
    * The applicable product field. Possible values: - TITLE - DESCRIPTION
    */
    'field'?: string;
    /**
    * The list of optimized text.
    */
    'items'?: Array<Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestionsItems>"
        }    ];

    static getAttributeTypeMap() {
        return Product202405GetRecommendedProductTitleAndDescriptionResponseDataProductsSuggestions.attributeTypeMap;
    }
}

