/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { Promotion202406GetCouponResponseDataCoupon } from './GetCouponResponseDataCoupon';

export class Promotion202406GetCouponResponseData {
    'coupon'?: Promotion202406GetCouponResponseDataCoupon;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "coupon",
            "baseName": "coupon",
            "type": "Promotion202406GetCouponResponseDataCoupon"
        }    ];

    static getAttributeTypeMap() {
        return Promotion202406GetCouponResponseData.attributeTypeMap;
    }
}

